"""Modelo actualizado V4

Revision ID: 1ee963521079
Revises: a77649073128
Create Date: 2025-05-24 21:20:19.527642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee963521079'
down_revision: Union[str, None] = 'a77649073128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('descargos', sa.Column('total', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descargos', 'total')
    # ### end Alembic commands ###
