"""Modelo actualizado V3

Revision ID: 779c1a3e0fa7
Revises: 
Create Date: 2025-05-24 20:12:59.431655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779c1a3e0fa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineas_factura', sa.Column('factura_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('lineas_factura_linea_transaccional_id_fkey'), 'lineas_factura', type_='foreignkey')
    op.create_foreign_key(None, 'lineas_factura', 'facturas', ['factura_id'], ['id'])
    op.drop_column('lineas_factura', 'linea_transaccional_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lineas_factura', sa.Column('linea_transaccional_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lineas_factura', type_='foreignkey')
    op.create_foreign_key(op.f('lineas_factura_linea_transaccional_id_fkey'), 'lineas_factura', 'lineas_transaccionales', ['linea_transaccional_id'], ['id'])
    op.drop_column('lineas_factura', 'factura_id')
    # ### end Alembic commands ###
