"""Modelo actualizado V3

Revision ID: a77649073128
Revises: 779c1a3e0fa7
Create Date: 2025-05-24 20:20:28.414020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77649073128'
down_revision: Union[str, None] = '779c1a3e0fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lineas_descargo', ['linea_transaccional_id'])
    op.add_column('lineas_factura', sa.Column('linea_transaccional_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'lineas_factura', ['linea_transaccional_id'])
    op.create_foreign_key(None, 'lineas_factura', 'lineas_transaccionales', ['linea_transaccional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lineas_factura', type_='foreignkey')
    op.drop_constraint(None, 'lineas_factura', type_='unique')
    op.drop_column('lineas_factura', 'linea_transaccional_id')
    op.drop_constraint(None, 'lineas_descargo', type_='unique')
    # ### end Alembic commands ###
